### ISSUE TITLE
OSL Central Load Balancer

### ISSUE THREAD

**Issue by armiller** [osuosl-cookbooks/osl-haproxy#7]
From our meeting we came to the conclusion to using multiple data bags for managing projects within haproxy. Within each databag you can pass in an array for the frontends, listeners, and backends which will get merged with all of the other project data bags in the chef run. Here is an example of the project databag.

```json
{
  "id": "mozillazine",
  "cluster": "osl",
  "frontend": {
    "http_https": [
      "acl mozillazine hdr(host) mozillazine.org",
      "use-backend mozillazine if mozillazine"
    ],
    "http": [
      "http-request redirect scheme https if !{ ssl_fc }",
     ],
  },
  "backend": {
    "mozillazine": [
      "server mozillazine-www1 140.x.x.x:80 weight 1 maxconn 100 check",
      "server mozillazine-www2 140.x.x.x:80 weight 1 maxconn 100 check"
     ]
  }
}
```

For the backends we have the option of using a default config for backends like we do with phpbb and instead pass individual attributes to override. If we decide to take this route it will mean more logic within the recipe that may have to be rewritten when we need a custom backend.

The frontends will be created with the lwrp in the recipe since we need them to pass in the merged arrays.

I also have the idea of adding a config check before we do the final service reload with:

`haproxy -f /etc/haproxy/haproxy.cfg -c`

**Comment by armiller** [comment]
ping @ramereth @jordane @bramwelt for review and thoughts

**Comment by ramereth** [comment]
I like this approach but I'm still not sure on it exactly. So a couple of things...

1. Frontends: Typically we want to use the same settings for both http and https with a few minor exceptions (bind port and X-Forwarded-Proto). So to me by default we should use both and deal with logic using ``ssl_fc``. I really don't want to have to duplicate two data bags that have the same information.
2. Your backend example isn't correct. There should be one backend with two servers in the backend (aka an array). However it will be likely that we have multiple backends with single servers (i.e. phpbb).
3. For a larger load balancer setup, the haproxy config is going to get rather large. Do we want to consider using an approach similar to what we're doing with orvsd-paas using files with hostnames we source? It wouldn't be difficult to make an LWRP to manage those files. This has the potential of simplify creating frontend/backends for simple stuff.
4. I really would like a saner and more built in way to manage ssl certificates being added and managed. Kind of hard to describe here but I'm not thrilled with how we're doing it with roles and attributes. IMO it should be done with a data bag too (at least the attributes?) I'm not sure..
5. I like the idea of adding a config syntax check

I'm going back and forth in my head about whether or not we just allow straight up haproxy configuration like you have above, or add some resources for things we use often (i.e. http -> https redirection). I think for a first go around doing it like this will be easier and we can figure out resources later if we feel like we should.

I'd like to see what a data bag might look like using phpbb and orvsd as an example (don't need to show the full config of orvsd, just enough to get an idea).

**Comment by armiller** [comment]
1. You don't need to duplicate any databags. You can see how it would work with the updated data bag example. Plus you would not have a bunch of extra `ssl_fc` within the `https` frontend.
2. I fixed the backend example
3. Does it matter how big the config files is if it is created by Chef? I don't thinks its worth the extra complexity.
4. I understand but that seems outside the scope of this issue.

**Comment by ramereth** [comment]
1. So with how that's setup I basically have to duplicate everything I'm doing? That can be prone to error. If you look at orvsd and phpbb you will see that both http/https are virtual the same with the settings. I really don't want to have to duplicate the configs and then make sure I copied the same config for each frontend.

**Comment by armiller** [comment]
The issue I see is that the duplication of `http` and `https` is not apparent in the databag. With the approach above its a straight 1 to 1 conversion. Duplicating lines is not difficult within a text editor and the config check would catch any misspelling errors before reloading the service. Plus most errors would be caught with basic code review.

**Comment by ramereth** [comment]
@armiller @jordane Let's try meeting together and talk about this more in person. I think we can sort this out quicker that way. Are you around tomorrow?

**Comment by jordane** [comment]
@ramereth I was assuming we'd bring it up in the innovation meeting this morning, like we discussed last week.

**Comment by ramereth** [comment]
We'll want to use an ``only_if`` like they do in the [apache2 cookbook](https://github.com/viverae-cookbooks/apache2/blob/master/recipes/default.rb#L205)

**Comment by jordane** [comment]
1. Use `http_https` for both frontends at the same time
2. Do syntax checking before restarting
3. One databag per project

**Comment by jordane** [comment]
2 PRs: one for adding this, one for doing source.

**Comment by jordane** [comment]
lock osl-haproxy in phpbb environment

**Comment by armiller** [comment]
@osuosl-cookbooks/chefs I am working on managing multiple ssl certs at the moment. Here are my thoughts. We use the `resource_from_hash` cookbook and define a `certificate` lwrp for each project that has a cert. Then we loop over the project databags, which will call each lwrp and add the certs to the node. From there we just append each cert location to the `bind` parameter.

We would also have a `default['osl-haproxy']['ssl_ciphers']` where we can define which ciphers we want to support or not.

**Comment by ramereth** [comment]
I'm all for using an LWRP and the resource_from_hash cookbook.
